version: '3.3'
services:
  vernemq:
      image: imamfahrurrofi/vernemq:1.12.6.2
      container_name: vernemq
      restart: always
      environment:
        DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'off'
        DOCKER_VERNEMQ_PLUGINS.vmq_passwd: 'on'
        DOCKER_VERNEMQ_PLUGINS.vmq_acl: 'on'
        DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
        DOCKER_VERNEMQ_USER_server: 'pass'
        DOCKER_VERNEMQ_USER_client: 'pass'
        DOCKER_VERNEMQ_USER_driver: 'pass'
        DOCKER_VERNEMQ_PERSISTENT_CLIENT_EXPIRATION: '1d'
        DOCKER_VERNEMQ_LEVELDB__MAXIMUM_MEMORY__PERCENT: 40
        DOCKER_VERNEMQ_LISTENER__WSS__CAFILE: './ssl/cacerts.pem'
        DOCKER_VERNEMQ_LISTENER__WSS__CERTFILE: './ssl/cert.pem'
        DOCKER_VERNEMQ_LISTENER__WSS__KEYFILE: './ssl/key.pem'
      expose:
        - '1883'
        - '8080'
        - '8443'
        - '8888'
      volumes:
        - './vmq.acl:/etc/vernemq/vmq.acl'
        - './ssl/:/etc/ssl/'